### ISSUE TITLE
Invalid Results of Joining of Records

### ISSUE THREAD

**Issue by jet4419** [yng-me/rcbms-app#144]
Hello Sir Bhas, eto po yung nakitang issue ni Maam Ella sa pagjoin ng two records. Okay yung sa Right Join pero hindi po tugma yung results pag ni Left Join.

**Left Join**

![left_join_2](https://github.com/yng-me/rcbms-app/assets/34343393/f6cecd37-0eeb-43d9-9409-35134fb8e3c6)
![left_join](https://github.com/yng-me/rcbms-app/assets/34343393/fd2f78b2-2c1b-46de-96b9-444605dd4f7a)

**Right Join**

![right_join_2](https://github.com/yng-me/rcbms-app/assets/34343393/0e81c0d5-0ba7-4049-9524-1ec926a04e36)
![right_join](https://github.com/yng-me/rcbms-app/assets/34343393/e0453c9e-aaa1-41ee-9f1d-1ee8b208af91)

**Comment by yng-me** [comment]
What you mean, hindi tugma? Dapat same count sila?

**Comment by jet4419** [comment]
"Opo. Pero may mga zero yung mga ages na walang papasok na hh members" ~ Ma'am Ella

**Comment by yng-me** [comment]
Kasi nga naka-"left join" kaya may lumabas talaga.
